<a href="https://colab.research.google.com/github/4060E046/AI_and_security/blob/master/10072020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ndarray(N-Dimensional Arrays)重要屬性:shape dimension
軸 (axis) 與維度 (dimension) 

In [1]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

ndarray資料型態(dtype)與型態轉換(astype)

In [2]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

下列程式執行後的結果為何?

In [3]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

1.使用Python內建的array()建立陣列

In [5]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])

2.使用numpy提供的創建函數建立陣列

In [ ]:
eye
zeros
ones
linspace
indices
diag
tile

In [8]:
import numpy as np
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

使用np.zeros建立陣列

In [9]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

使用np.ones建立陣列

In [10]:
import numpy as np
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

使用np.arange建立陣列

In [11]:
import numpy as np
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

使用np.linspace建立陣列

In [12]:
import numpy as np
np.linspace(1., 4., 6) # start, end, num

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

使用np.linspace建立陣列

In [13]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

使用np.linspace建立陣列

In [14]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

使用np.linspace建立陣列

In [15]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

使用np.indices建立陣列

In [16]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

使用np.diag建立陣列

In [17]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, 2)
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 2))
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

3.直接生成使用genfromtxt()方法建立陣列

In [18]:
import csv
import numpy as np

x = '''1,3,2,3,1,2,3,4
2,4,5,0.6,5,6,7,8
3,7,8,9,9,10,11,12
4,1,1.1,1.2,13,14,15,16
'''
with open("abc.txt",mode="w",encoding="utf-8") as file:
  file.write(x)
file.close()

np.genfromtxt('abc.txt', delimiter=',', invalid_raise = False)

array([[ 1. ,  3. ,  2. ,  3. ,  1. ,  2. ,  3. ,  4. ],
       [ 2. ,  4. ,  5. ,  0.6,  5. ,  6. ,  7. ,  8. ],
       [ 3. ,  7. ,  8. ,  9. ,  9. , 10. , 11. , 12. ],
       [ 4. ,  1. ,  1.1,  1.2, 13. , 14. , 15. , 16. ]])

下列程式執行後的結果為何?

In [19]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

下列程式執行後的結果為何?

In [20]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

NUMPY ndarray 運算(Array shape manipulation)

reshape

In [22]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [23]:
import numpy as np
y = np.arange(2,10).reshape(4,2)
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

ravel

In [24]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [25]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

T

In [26]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

newaxis

In [27]:
import numpy as np
ar=ar[:, np.newaxis]; ar.shape
ar

array([[[ 1,  2,  3,  4,  5]],

       [[10, 11, 12, 13, 14]]])

下列程式執行後的結果為何?

In [28]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [29]:
import numpy as np
ar=np.array([14,15,16])
ar=ar[:, np.newaxis]
ar.shape

(3, 1)

ndarray的索引(index)與切片運算(slice)

1.索引(index)

In [30]:
import numpy as np
x = np.arange(2,10)
# x
print(x[0])
print(x[-2])
print(x[-1])
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[1,2]

2
8
9


7

2.切片運算(slice)

In [31]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:5:2]
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:6:2]
import numpy as np
ar=2*np.arange(6)
# ar
ar[:4]

array([0, 2, 4, 6])

ndarray的Reduction 運算:prod()|sum()|mean()|median()

prod()
sum()
mean()
median(ar)

In [32]:
import numpy as np
ar=np.arange(1,5)
ar.prod()

24

In [33]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.sum()

54

In [34]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.mean()

6.0

In [35]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
np.median(ar)

6.0

ufunc(Universal Functions):Fast Element-Wise Array Functions

sqrt

In [36]:
import numpy as np
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

exp


In [37]:
import numpy as np
arr = np.arange(10)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

[5]多Numpy ndarray的各種運算(A矩陣與B矩陣間的運算)

加法運算

In [38]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

乘法運算

In [39]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# arr
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
import numpy as np
ar=np.array([[1,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar*ar2

array([[2, 2],
       [2, 2]])

dot運算

In [41]:
import numpy as np
ar=np.array([[1,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

[6]ndarray 運算的Broadcasting(廣播機制)

In [42]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)
import numpy as np
np.arange(3) + 5
import numpy as np
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

[7]使用<Numpy random模組>產生隨機資料

In [44]:
import numpy as np
np.random.randint(1,5)


3

In [45]:
import numpy as np
np.random.randint(-5,5,size=(2,2))

array([[ 3, -4],
       [-4,  2]])

In [46]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6) 
x1

array([5, 0, 3, 3, 7, 9])

In [47]:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [48]:
import numpy as np
np.random.seed(0)
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

NUMPY ndarray 運算

In [52]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [53]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'same')

array([1. , 2.5, 4. ])

In [54]:
import numpy as np
np.convolve([1,2,3],[0,1,0.5], 'valid')

array([2.5])

NUMPY ndarray(N-Dimensional Arrays)檔案輸入與輸出

In [ ]:
https://ithelp.ithome.com.tw/articles/10196167
save()
load()

NUMPY ndarray 運算 - 排序sort

In [56]:
import numpy as np
ar=np.array([[3,2],[10,-1]])
# ar
ar.sort(axis=1)
ar

array([[ 2,  3],
       [-1, 10]])

**龍大大 我的億 大樂透 開獎中心**

In [57]:
import random as rand

list1 = rand.sample(range(1,50), 7)

special = list1.pop()

list1.sort()

print("龍大大 我的億 大樂透 開獎中心")
print("本期大樂透中獎號碼為：", end="")
for i in range(0,6):
    if i == 5:    print(str(list1[i]))
    else:    print(str(list1[i]), end=", ")
print("本期大樂透特別號為：" + str(special))

龍大大 我的億 大樂透 開獎中心
本期大樂透中獎號碼為：10, 11, 24, 32, 40, 43
本期大樂透特別號為：33
